#!/usr/bin/env ruby

#
#     DUALCRAFT
#           // now in color //

# Changelog:
#   0.1:
#     Flat world gen
#     Mountainy world gen based off asciicraft
#     Dirt, stone, grass
#     Basic entities
#
#
module Dualcraft
  NAME = "Dualcraft by Nick"
  VERSION = 0.1 # major.minor

  def self.run
    puts("#{NAME} version #{VERSION}")
    
    puts("Loading gosu...")
    require("gosu")
    puts("Loading socket...")
    require("socket")
    puts("Loading JSON...")
    require("json")
    
    puts("Loading classes...")
    $dualcraft_blocks = []
    $dualcraft_entities = []
    Dir.entries("class").sort.each do |entry|
      if entry.split(".")[-1] == "rb" then 
        puts("  ./class/#{entry}")
        require("./class/#{entry}")
      end
    end
    
    if ARGV[0] == nil then
      username = "Player#{rand(100000)}"
    else
      username = ARGV[0]
    end
    
    if $dualcraft_debug then return end
    Game.new(username).show
  end
end

begin
  Dualcraft.run
rescue
  puts("#{$!} #{$@}")
  gets
end

